name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Setup npmrc for GitHub Packages
        run: |
          echo "@vipelar:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.VIPELAR_PACKAGES_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Build
        env:
          DOTENV_PRIVATE_KEY_LOCAL: ${{ secrets.DOTENV_PRIVATE_KEY_LOCAL }}
        run: pnpm build
